    name: Peergos
    services:
            image: ghcr.io/peergos/web-ui::master
            command:
                - daemon
                - -listen-host
                - 0.0.0.0
            ports:
                - id: web
                  port: 8000
                  type: HTTP
            volumes:
                - id: data
                  dir: /opt/peergos/data
            healthCheck:
                type: HTTP
                port: web
                http:
                    path: /
            domainKey: mediateurs.7enjeux.org
