name: 7enjeux
services:
  nginx:
    image: nginx:latest
     restart: unless-stopped
    ports:
      - "80"
      - "443"
  web-ui:
    image: ghcr.io/peergos/web-ui:master
    volumes:
      - nginx-config:/etc/nginx
      - nginx-html:/usr/share/nginx/html
      - /opt/peergos/data
        command: daemon -listen-host 0.0.0.0 -public-domain mediateurs.7enjeux.org -public-server
            true -announce-ipfs-addresses
            /ip4/$IP/tcp/4001,/ip4/$IP/udp/4001/quic-v1 -log-to-console true      

        environment:
            - PEERGOS_HEADLESS=true
networks:
  my_network:
    external: true

