name: 7enjeux
services:
    web-ui:
        volumes:
            - /opt/peergos/data
        image: ghcr.io/peergos/web-ui:master
        command: daemon -listen-host 0.0.0.0 -public-domain 7enjeux.org -public-server
            true -announce-ipfs-addresses
            /ip4/$IP/tcp/4001,/ip4/$IP/udp/4001/quic-v1 -log-to-console true
backend:
    expose:
      - "8000"

networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.<nom-unique>.rule=Host(`7enjeux.org`)"
      - "traefik.http.routers.<nom-unique>.entrypoints=websecure"
      - "traefik.http.routers.<nom-unique>.tls.certResolver=letsencrypt"
      - "traefik.http.services.<nom-unique>.loadbalancer.server.port=443"
networks:
  dokploy-network:
    external: true
